# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105gKlJvbNbLkg5qYIlw7anHJR8S9V622
"""

import os, re, joblib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import gradio as gr

DRIVE_ROOT = "/content/drive/MyDrive/Dissertation"
DATA_PATH = os.path.join(DRIVE_ROOT, "data/processed")
MODEL_DIR = os.path.join(DRIVE_ROOT, "models")

song_pool = pd.read_csv(os.path.join(DATA_PATH, "song_pool_predictions.csv"))
df_full = pd.read_csv(os.path.join(DATA_PATH, "deam_full_with_ids.csv"))
trained_cols = joblib.load(os.path.join(MODEL_DIR, "feature_columns.pkl"))
shap_v = np.load(os.path.join(DATA_PATH, "shap_valence.npy"))
shap_a = np.load(os.path.join(DATA_PATH, "shap_arousal.npy"))


def infer_mood(ids):
    lis = song_pool[song_pool["song_id"].isin(ids)]
    return {
        "valence": lis["pred_valence"].mean(),
        "arousal": lis["pred_arousal"].mean(),
        "spread": np.sqrt(lis["pred_valence"].var() + lis["pred_arousal"].var()),
        "n": len(lis),
    }

def label_quadrant(v, a, threshold=0.15):
    if abs(v) < threshold and abs(a) < threshold:
        return "Neutral / Ambiguous"
    if v >= 0 and a >= 0: return "Excited / Elated"
    if v < 0 and a >= 0:  return "Angry / Stressed"
    if v < 0 and a < 0:   return "Sad / Depressed"
    return "Calm / Content"


def rec_songs(v, a, n=5, exclude_ids=None):
    pool = song_pool.copy()
    if exclude_ids:
        pool = pool[~pool["song_id"].isin(exclude_ids)]
    pool["dist"] = np.sqrt((pool["pred_valence"]-v)**2 + (pool["pred_arousal"]-a)**2)
    return pool.sort_values("dist").head(n).reset_index(drop=True)


def circumplex_fig(mood, listened, recommended):
    fig, ax = plt.subplots(figsize=(6, 5.5))
    ax.scatter(song_pool["pred_valence"], song_pool["pred_arousal"], alpha=0.12, color="grey", s=12)
    lis = song_pool[song_pool["song_id"].isin(listened)]
    ax.scatter(lis["pred_valence"], lis["pred_arousal"], color="steelblue", s=70, label="your listens")
    rec = song_pool[song_pool["song_id"].isin(recommended)]
    ax.scatter(rec["pred_valence"], rec["pred_arousal"], color="seagreen", s=70, marker="s", label="recommended")
    ax.scatter(mood["valence"], mood["arousal"], color="crimson", marker="*", s=400, edgecolors="black", label="your mood")
    ax.axhline(0, color="black", ls="--", lw=0.8)
    ax.axvline(0, color="black", ls="--", lw=0.8)
    ax.set_xlabel("Valence (negative -> positive)")
    ax.set_ylabel("Arousal (calm -> energetic)")
    ax.legend(fontsize=8, loc="upper left")
    plt.tight_layout()
    return fig


def shap_fig(song_id, top_n=8):
    i = df_full.index[df_full["song_id"] == song_id][0]
    row = song_pool[song_pool["song_id"] == song_id].iloc[0]
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
    for ax, (name, sv, pred) in zip(axes, [("Valence", shap_v, row["pred_valence"]),
                                           ("Arousal", shap_a, row["pred_arousal"])]):
        c = sv[i]
        order = np.argsort(np.abs(c))[::-1][:top_n][::-1]
        vals = c[order]
        ax.barh(range(len(vals)), vals, color=["seagreen" if v > 0 else "crimson" for v in vals])
        ax.set_yticks(range(len(vals)))
        ax.set_yticklabels([trained_cols[j] for j in order], fontsize=7)
        ax.axvline(0, color="black", lw=0.8)
        ax.set_title(f"{name} = {pred:.3f}", fontsize=10)
        ax.grid(axis="x", ls=":", alpha=0.4)
    fig.suptitle(f"{row['title']} - {row['Artist']}", fontsize=11)
    plt.tight_layout()
    return fig


CHOICES = [f"{r.title} - {r.Artist} ({r.Genre}) [{r.song_id}]" for r in song_pool.itertuples()]
TO_ID = {c: int(c.rsplit("[", 1)[1].rstrip("]")) for c in CHOICES}


def analyse(selected, n_recs):
    if not selected:
        return None, "Select at least one song.", pd.DataFrame(), None
    ids = [TO_ID[s] for s in selected]
    mood = infer_mood(ids)
    coherence = "consistent" if mood["spread"] < 0.35 else "mixed - estimate less certain"
    summary = (f"### {label_quadrant(mood['valence'], mood['arousal'])}\n"
               f"valence **{mood['valence']:.3f}** | arousal **{mood['arousal']:.3f}**\n\n"
               f"{mood['n']} songs | session is {coherence} (spread {mood['spread']:.3f})")
    recs = rec_songs(mood["valence"], mood["arousal"], n=int(n_recs), exclude_ids=ids)
    table = recs[["title", "Artist", "Genre", "pred_valence", "pred_arousal", "dist"]].round(3)
    return circumplex_fig(mood, ids, recs["song_id"].tolist()), summary, table, int(recs.iloc[0]["song_id"])


def build_ui():
    with gr.Blocks(title="Emotion-Aware Music Recommender") as demo:
        gr.Markdown("# Emotion-aware music recommender")
        gr.Markdown("Select songs you have been listening to. Your affective state is inferred as a centroid in Russell's circumplex space.")
        with gr.Row():
            with gr.Column():
                sel = gr.Dropdown(CHOICES, multiselect=True, label="Your recent listens", max_choices=8)
                n = gr.Slider(3, 10, value=5, step=1, label="Recommendations")
                btn = gr.Button("Analyse my mood", variant="primary")
                mood_md = gr.Markdown()
            with gr.Column():
                plot = gr.Plot(label="Circumplex space")
        gr.Markdown("### Recommended for you")
        table = gr.Dataframe()
        top = gr.State()
        xai_btn = gr.Button("Explain top recommendation")
        xai = gr.Plot()
        btn.click(analyse, [sel, n], [plot, mood_md, table, top])
        xai_btn.click(lambda s: shap_fig(int(s)) if s else None, [top], [xai])
    return demo


if __name__ == "__main__":
    build_ui().launch(share=True)