# -*- coding: utf-8 -*-
"""MERS_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs9BHKhPjnvKpi5GcmZZjxz-G6soid6l

This notebook is only for code reusability across all notebooks in my dissertation project
"""

import os
import joblib
import pandas as pd

DRIVE_ROOT = "/content/drive/MyDrive/Dissertation"
DATA_PATH = os.path.join(DRIVE_ROOT, "data/processed")
MODEL_DIR = os.path.join(DRIVE_ROOT, "models")

def load_models():
    return (
        joblib.load(os.path.join(MODEL_DIR, "valence_model.pkl")),
        joblib.load(os.path.join(MODEL_DIR, "arousal_model.pkl")),
        joblib.load(os.path.join(MODEL_DIR, "feature_columns.pkl")),
        joblib.load(os.path.join(MODEL_DIR, "scaler.pkl")),
    )

def load_song_pool():
    return pd.read_csv(os.path.join(DATA_PATH, "song_pool_predictions.csv"))

def load_full_dataset():
    return pd.read_csv(os.path.join(DATA_PATH, "deam_full_with_ids.csv"))

